build: Add type checking
Workarounds for TypeScript shortcomings:

* `@typedef` can't be namespaced in JS files, thus mandating awkward
  constructs like `/** @import { Logger } from './qtap.js' */`.

* There is no way to apply a type to a `catch` clause in JS files.
  The workaround is to re-assign it to a local variable and type that
  like `catch (e) { /* @type {any} */ const err = e;`.

* There is no way to disable type checking for an entire block,
  function, or otherwise multiple lines, thus mandating lots of
  `// @ts-ignore` lines for the same problem, or to move the code
  out into a separate file where the entire file is ignored (as I
  ended up doing for client.js).

  Reported 8y ago, https://github.com/Microsoft/TypeScript/issues/19573.

* `@types/node` lacks Error.code or Error.stack definitinos,
  thus regularly requiring use of the above workarounds.
  Reported 3y ago, https://github.com/DefinitelyTyped/DefinitelyTyped/issues/59692.

* The `noUnusedLocals` rule is broken, making a paradoxal claim.

  ```
  /** @import { Logger } from './qtap.js' */

  /**
    * @param {Logger} logger
    */
  ```
  The above makes sense, and passes, until noUnusedLocals is enabled.
  Then it fails:

  ```
  error TS6133: 'Logger' is declared but its value is never read.
  /** @import { Logger } from './qtap.js' */
  ```

  Removing the import, of course, causes a more severe error instead:
  ```
  error TS2304: Cannot find name 'Logger'.
  * @param {Logger} logger
  ```

  Reported 2y ago, closed as wontfix.
  https://github.com/microsoft/TypeScript/issues/54042

* The `noUnusedParameters` errors on unused arguments before arguments
  that are required and used. It appears to be unconfigurable and thus
  serves no purpose. Leave disabled in favor of ESLint no-unused-vars.

* The `noImplicitAny: false` setting, while ostensibly turning some
  checks off, makes array behaviour more strict, changing default
  from `any[]` to an awkward `never[]`.

  Reported 5y ago, https://stackoverflow.com/a/57563877/319266

  ```
  const seen = { plan: null, asserts: [] };

  p.on('assert', function (result) {
    //> error TS2345: Argument of type 'any' is not assignable to parameter of type 'never'.
    seen.asserts.push(result);
  })
  ```